# - Try to find CKinematics (https://github.com/cbpark/CKinematics)
# Once done this will define
#  CKINEMATICS_FOUND - System has CKinematics
#  CKINEMATICS_INCLUDE_DIRS - The CKinematics include directories
#  CKINEMATICS_LIBRARIES - The libraries needed to use CKinematics
#  CKINEMATICS_DEFINITIONS - Compiler switches required for using CKinematics

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_CKINEMATICS QUIET CKinematics)
SET(CKINEMATICS_DEFINITIONS ${PC_CKINEMATICS_CFLAGS_OTHER})

FIND_PATH(CKINEMATICS_INCLUDE_DIR CKinematics/kinematics.h
          HINTS ${PC_CKINEMATICS_INCLUDEDIR} ${PC_CKINEMATICS_INCLUDE_DIRS}
          PATH_SUFFIXES CKinematics)

FIND_LIBRARY(CKINEMATICS_LIBRARY NAMES CKinematics libCKinematics
             HINTS ${PC_CKINEMATICS_LIBDIR} ${PC_CKINEMATICS_LIBRARY_DIRS})

SET(CKINEMATICS_LIBRARIES ${CKINEMATICS_LIBRARY})
SET(CKINEMATICS_INCLUDE_DIRS ${CKINEMATICS_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CKinematics DEFAULT_MSG
                                  CKINEMATICS_LIBRARY CKINEMATICS_INCLUDE_DIR)

MARK_AS_ADVANCED(CKINEMATICS_INCLUDE_DIR CKINEMATICS_LIBRARY)